version: "3.9"

services:
  frontend:
    build:
      context: ./bactounes
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - default
