worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;


    include mime.types;
    

    
   
    default_type application/octet-stream;

  

    proxy_intercept_errors on;

    add_header Cache-Control "no-store, must-revalidate";

    server {
        listen 80;
        server_name 51.178.53.52;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        error_page 502 503 504 /custom_50x.html;
        error_page 404 /custom_404.html;

        location = /custom_50x.html {
            root /usr/share/nginx/html;
            internal;
        }

        location = /custom_404.html {
            root /usr/share/nginx/html;
            internal;
        }

        # Reverse proxies

       
       
        # Secure uploads






    }
}
